(*
    Tests for: Daniel`ARC`ARCPruneOutputsForRuleFinding
    
    To run these tests:
    
        << DevTools`
        << Daniel`ARC`
        RunUnitTests[Daniel`ARC`ARCPruneOutputsForRuleFinding]
    
    Author: danielb
*)

Test[
    Utility`ReplaceAssociationsWithUnevaluatedAssociations[
        DevTools`TestingTools`SlowTest[
            DevTools`ERP`NormalizeOutput[
                DevTools`ERP`NormalizeOutput["Key" -> "OutputComponentUUID"][
                    Daniel`ARC`ARCPruneOutputsForRuleFinding[
                        Utility`ReturnIfFailure[
                            Daniel`ARC`ARCFindObjectMapping[
                                Daniel`ARC`ARCParseFile[file = "0ca9ddb6"]["Train", 2]
                            ]
                        ],
                        1
                    ]
                ]
            ]
        ]
    ]
    ,
    {
        <|
            "Image" -> Daniel`ARC`ARCScene[{{8}}],
            "PixelPositions" -> {{1, 4}},
            "Shape" -> <|"Name" -> "Pixel"|>,
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                <|"Name" -> "Pixel"|>,
                <|"Name" -> "Square"|>,
                <|"Name" -> "Rectangle"|>,
                <|"Name" -> "Square", "Filled" -> True|>,
                <|"Name" -> "Rectangle", "Filled" -> True|>
            },
            "Colors" -> {8},
            "Color" -> 8,
            "Position" -> {1, 4},
            "Y" -> 1,
            "X" -> 4,
            "YInverse" -> 9,
            "XInverse" -> 6,
            "Y2" -> 1,
            "X2" -> 4,
            "Y2Inverse" -> 9,
            "X2Inverse" -> 6,
            "Width" -> 1,
            "Height" -> 1,
            "Length" -> 1,
            "PrimarySizeDimension" -> "None",
            "AspectRatio" -> 1,
            "Area" -> 1,
            "FilledArea" -> 1,
            "FilledProportion" -> 1.,
            "ColorUseCount" -> 1,
            "YRelative" -> 0,
            "XRelative" -> 0,
            "Width.Rank" -> 1,
            "Width.InverseRank" -> 1,
            "Height.Rank" -> 1,
            "Height.InverseRank" -> 1,
            "Length.Rank" -> 1,
            "Length.InverseRank" -> 1,
            "Y.Rank" -> 5,
            "Y.InverseRank" -> 1,
            "X.Rank" -> 2,
            "X.InverseRank" -> 3,
            "Y2.Rank" -> 5,
            "Y2.InverseRank" -> 1,
            "X2.Rank" -> 2,
            "X2.InverseRank" -> 3,
            "PrimarySizeDimension.Rank" -> 1,
            "PrimarySizeDimension.InverseRank" -> 1,
            "AspectRatio.Rank" -> 1,
            "AspectRatio.InverseRank" -> 1,
            "Area.Rank" -> 1,
            "Area.InverseRank" -> 1,
            "FilledArea.Rank" -> 1,
            "FilledArea.InverseRank" -> 1,
            "FilledProportion.Rank" -> 1,
            "FilledProportion.InverseRank" -> 1,
            "ColorUseCount.Rank" -> 2,
            "ColorUseCount.InverseRank" -> 1
        |> -> <|
            "Same" -> True,
            "Example" -> 1,
            "Input" -> <|
                "UUID" -> 0,
                "Image" -> Daniel`ARC`ARCScene[{{8}}],
                "PixelPositions" -> {{1, 4}},
                "Shape" -> <|"Name" -> "Pixel"|>,
                "Shapes" -> {
                    <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                    <|"Name" -> "Pixel"|>,
                    <|"Name" -> "Square"|>,
                    <|"Name" -> "Rectangle"|>,
                    <|"Name" -> "Square", "Filled" -> True|>,
                    <|"Name" -> "Rectangle", "Filled" -> True|>
                },
                "Colors" -> {8},
                "Color" -> 8,
                "Position" -> {1, 4},
                "Y" -> 1,
                "X" -> 4,
                "YInverse" -> 9,
                "XInverse" -> 6,
                "Y2" -> 1,
                "X2" -> 4,
                "Y2Inverse" -> 9,
                "X2Inverse" -> 6,
                "Width" -> 1,
                "Height" -> 1,
                "Length" -> 1,
                "PrimarySizeDimension" -> "None",
                "AspectRatio" -> 1,
                "Area" -> 1,
                "FilledArea" -> 1,
                "FilledProportion" -> 1.,
                "ColorUseCount" -> 1,
                "YRelative" -> 0,
                "XRelative" -> 0,
                "Width.Rank" -> 1,
                "Width.InverseRank" -> 1,
                "Height.Rank" -> 1,
                "Height.InverseRank" -> 1,
                "Length.Rank" -> 1,
                "Length.InverseRank" -> 1,
                "Y.Rank" -> 5,
                "Y.InverseRank" -> 1,
                "X.Rank" -> 2,
                "X.InverseRank" -> 3,
                "Y2.Rank" -> 5,
                "Y2.InverseRank" -> 1,
                "X2.Rank" -> 2,
                "X2.InverseRank" -> 3,
                "PrimarySizeDimension.Rank" -> 1,
                "PrimarySizeDimension.InverseRank" -> 1,
                "AspectRatio.Rank" -> 1,
                "AspectRatio.InverseRank" -> 1,
                "Area.Rank" -> 1,
                "Area.InverseRank" -> 1,
                "FilledArea.Rank" -> 1,
                "FilledArea.InverseRank" -> 1,
                "FilledProportion.Rank" -> 1,
                "FilledProportion.InverseRank" -> 1,
                "ColorUseCount.Rank" -> 2,
                "ColorUseCount.InverseRank" -> 1
            |>
        |>,
        <|
            "Image" -> Daniel`ARC`ARCScene[{{2}}],
            "PixelPositions" -> {{3, 7}},
            "Shape" -> <|"Name" -> "Pixel"|>,
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                <|"Name" -> "Pixel"|>,
                <|"Name" -> "Square"|>,
                <|"Name" -> "Rectangle"|>,
                <|"Name" -> "Square", "Filled" -> True|>,
                <|"Name" -> "Rectangle", "Filled" -> True|>
            },
            "Colors" -> {2},
            "Color" -> 2,
            "Position" -> {3, 7},
            "Y" -> 3,
            "X" -> 7,
            "YInverse" -> 7,
            "XInverse" -> 3,
            "Y2" -> 3,
            "X2" -> 7,
            "Y2Inverse" -> 7,
            "X2Inverse" -> 3,
            "Width" -> 1,
            "Height" -> 1,
            "Length" -> 1,
            "PrimarySizeDimension" -> "None",
            "AspectRatio" -> 1,
            "Area" -> 1,
            "FilledArea" -> 1,
            "FilledProportion" -> 1.,
            "ColorUseCount" -> 2,
            "YRelative" -> 0,
            "XRelative" -> 0,
            "Width.Rank" -> 1,
            "Width.InverseRank" -> 1,
            "Height.Rank" -> 1,
            "Height.InverseRank" -> 1,
            "Length.Rank" -> 1,
            "Length.InverseRank" -> 1,
            "Y.Rank" -> 4,
            "Y.InverseRank" -> 2,
            "X.Rank" -> 1,
            "X.InverseRank" -> 4,
            "Y2.Rank" -> 4,
            "Y2.InverseRank" -> 2,
            "X2.Rank" -> 1,
            "X2.InverseRank" -> 4,
            "PrimarySizeDimension.Rank" -> 1,
            "PrimarySizeDimension.InverseRank" -> 1,
            "AspectRatio.Rank" -> 1,
            "AspectRatio.InverseRank" -> 1,
            "Area.Rank" -> 1,
            "Area.InverseRank" -> 1,
            "FilledArea.Rank" -> 1,
            "FilledArea.InverseRank" -> 1,
            "FilledProportion.Rank" -> 1,
            "FilledProportion.InverseRank" -> 1,
            "ColorUseCount.Rank" -> 1,
            "ColorUseCount.InverseRank" -> 2,
            "OutputComponentUUID" -> _String
        |> -> <|
            "Image" -> Daniel`ARC`ARCScene[{{4, -1, 4}, {-1, 2, -1}, {4, -1, 4}}],
            "Shape" -> Daniel`ARC`ARCScene[{{10, -1, 10}, {-1, 10, -1}, {10, -1, 10}}],
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{4, -1, 4}, {-1, 2, -1}, {4, -1, 4}}]|>
            },
            "Position" -> {2, 6},
            "Y" -> 2,
            "X" -> 6,
            "YInverse" -> 8,
            "XInverse" -> 4,
            "X2" -> 8,
            "Y2" -> 4,
            "X2Inverse" -> 2,
            "Y2Inverse" -> 6,
            "Width" -> 3,
            "Height" -> 3,
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> -1,
                                "YInverse" -> -1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 2,
                        "X" -> 6,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> 1,
                                "YInverse" -> -1,
                                "XInverse" -> 1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 2,
                        "X" -> 8,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> 1,
                                "X" -> -1,
                                "YInverse" -> 1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 4,
                        "X" -> 6,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> 1,
                                "X" -> 1,
                                "YInverse" -> 1,
                                "XInverse" -> 1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 4,
                        "X" -> 8,
                        "Color" -> 4
                    |>
                }
            |>,
            "Example" -> 1,
            "Input" -> <|
                "UUID" -> 0,
                "Image" -> Daniel`ARC`ARCScene[{{2}}],
                "PixelPositions" -> {{3, 7}},
                "Shape" -> <|"Name" -> "Pixel"|>,
                "Shapes" -> {
                    <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                    <|"Name" -> "Pixel"|>,
                    <|"Name" -> "Square"|>,
                    <|"Name" -> "Rectangle"|>,
                    <|"Name" -> "Square", "Filled" -> True|>,
                    <|"Name" -> "Rectangle", "Filled" -> True|>
                },
                "Colors" -> {2},
                "Color" -> 2,
                "Position" -> {3, 7},
                "Y" -> 3,
                "X" -> 7,
                "YInverse" -> 7,
                "XInverse" -> 3,
                "Y2" -> 3,
                "X2" -> 7,
                "Y2Inverse" -> 7,
                "X2Inverse" -> 3,
                "Width" -> 1,
                "Height" -> 1,
                "Length" -> 1,
                "PrimarySizeDimension" -> "None",
                "AspectRatio" -> 1,
                "Area" -> 1,
                "FilledArea" -> 1,
                "FilledProportion" -> 1.,
                "ColorUseCount" -> 2,
                "YRelative" -> 0,
                "XRelative" -> 0,
                "Width.Rank" -> 1,
                "Width.InverseRank" -> 1,
                "Height.Rank" -> 1,
                "Height.InverseRank" -> 1,
                "Length.Rank" -> 1,
                "Length.InverseRank" -> 1,
                "Y.Rank" -> 4,
                "Y.InverseRank" -> 2,
                "X.Rank" -> 1,
                "X.InverseRank" -> 4,
                "Y2.Rank" -> 4,
                "Y2.InverseRank" -> 2,
                "X2.Rank" -> 1,
                "X2.InverseRank" -> 4,
                "PrimarySizeDimension.Rank" -> 1,
                "PrimarySizeDimension.InverseRank" -> 1,
                "AspectRatio.Rank" -> 1,
                "AspectRatio.InverseRank" -> 1,
                "Area.Rank" -> 1,
                "Area.InverseRank" -> 1,
                "FilledArea.Rank" -> 1,
                "FilledArea.InverseRank" -> 1,
                "FilledProportion.Rank" -> 1,
                "FilledProportion.InverseRank" -> 1,
                "ColorUseCount.Rank" -> 1,
                "ColorUseCount.InverseRank" -> 2,
                "OutputComponentUUID" -> _String
            |>
        |>,
        <|
            "Image" -> Daniel`ARC`ARCScene[{{1}}],
            "PixelPositions" -> {{4, 3}},
            "Shape" -> <|"Name" -> "Pixel"|>,
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                <|"Name" -> "Pixel"|>,
                <|"Name" -> "Square"|>,
                <|"Name" -> "Rectangle"|>,
                <|"Name" -> "Square", "Filled" -> True|>,
                <|"Name" -> "Rectangle", "Filled" -> True|>
            },
            "Colors" -> {1},
            "Color" -> 1,
            "Position" -> {4, 3},
            "Y" -> 4,
            "X" -> 3,
            "YInverse" -> 6,
            "XInverse" -> 7,
            "Y2" -> 4,
            "X2" -> 3,
            "Y2Inverse" -> 6,
            "X2Inverse" -> 7,
            "Width" -> 1,
            "Height" -> 1,
            "Length" -> 1,
            "PrimarySizeDimension" -> "None",
            "AspectRatio" -> 1,
            "Area" -> 1,
            "FilledArea" -> 1,
            "FilledProportion" -> 1.,
            "ColorUseCount" -> 2,
            "YRelative" -> 0,
            "XRelative" -> 0,
            "Width.Rank" -> 1,
            "Width.InverseRank" -> 1,
            "Height.Rank" -> 1,
            "Height.InverseRank" -> 1,
            "Length.Rank" -> 1,
            "Length.InverseRank" -> 1,
            "Y.Rank" -> 3,
            "Y.InverseRank" -> 3,
            "X.Rank" -> 3,
            "X.InverseRank" -> 2,
            "Y2.Rank" -> 3,
            "Y2.InverseRank" -> 3,
            "X2.Rank" -> 3,
            "X2.InverseRank" -> 2,
            "PrimarySizeDimension.Rank" -> 1,
            "PrimarySizeDimension.InverseRank" -> 1,
            "AspectRatio.Rank" -> 1,
            "AspectRatio.InverseRank" -> 1,
            "Area.Rank" -> 1,
            "Area.InverseRank" -> 1,
            "FilledArea.Rank" -> 1,
            "FilledArea.InverseRank" -> 1,
            "FilledProportion.Rank" -> 1,
            "FilledProportion.InverseRank" -> 1,
            "ColorUseCount.Rank" -> 1,
            "ColorUseCount.InverseRank" -> 2,
            "OutputComponentUUID" -> _String
        |> -> <|
            "Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, 1, 7}, {-1, 7, -1}}],
            "Shape" -> Daniel`ARC`ARCScene[{{-1, 10, -1}, {10, 10, 10}, {-1, 10, -1}}],
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, 1, 7}, {-1, 7, -1}}]|>
            },
            "Position" -> {3, 2},
            "Y" -> 3,
            "X" -> 2,
            "YInverse" -> 7,
            "XInverse" -> 8,
            "X2" -> 4,
            "Y2" -> 5,
            "X2Inverse" -> 6,
            "Y2Inverse" -> 5,
            "Width" -> 3,
            "Height" -> 3,
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, -1, 7}, {-1, 7, -1}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> -1,
                                "YInverse" -> -1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> Daniel`ARC`ARCScene[
                            {{-1, 10, -1}, {10, -1, 10}, {-1, 10, -1}}
                        ],
                        "Shapes" -> {
                            <|
                                "Image" -> Daniel`ARC`ARCScene[
                                    {{-1, 10, -1}, {10, -1, 10}, {-1, 10, -1}}
                                ]
                            |>
                        },
                        "Width" -> 3,
                        "Height" -> 3,
                        "Y" -> 3,
                        "X" -> 2,
                        "Color" -> 7
                    |>
                }
            |>,
            "Example" -> 1,
            "Input" -> <|
                "UUID" -> 0,
                "Image" -> Daniel`ARC`ARCScene[{{1}}],
                "PixelPositions" -> {{4, 3}},
                "Shape" -> <|"Name" -> "Pixel"|>,
                "Shapes" -> {
                    <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                    <|"Name" -> "Pixel"|>,
                    <|"Name" -> "Square"|>,
                    <|"Name" -> "Rectangle"|>,
                    <|"Name" -> "Square", "Filled" -> True|>,
                    <|"Name" -> "Rectangle", "Filled" -> True|>
                },
                "Colors" -> {1},
                "Color" -> 1,
                "Position" -> {4, 3},
                "Y" -> 4,
                "X" -> 3,
                "YInverse" -> 6,
                "XInverse" -> 7,
                "Y2" -> 4,
                "X2" -> 3,
                "Y2Inverse" -> 6,
                "X2Inverse" -> 7,
                "Width" -> 1,
                "Height" -> 1,
                "Length" -> 1,
                "PrimarySizeDimension" -> "None",
                "AspectRatio" -> 1,
                "Area" -> 1,
                "FilledArea" -> 1,
                "FilledProportion" -> 1.,
                "ColorUseCount" -> 2,
                "YRelative" -> 0,
                "XRelative" -> 0,
                "Width.Rank" -> 1,
                "Width.InverseRank" -> 1,
                "Height.Rank" -> 1,
                "Height.InverseRank" -> 1,
                "Length.Rank" -> 1,
                "Length.InverseRank" -> 1,
                "Y.Rank" -> 3,
                "Y.InverseRank" -> 3,
                "X.Rank" -> 3,
                "X.InverseRank" -> 2,
                "Y2.Rank" -> 3,
                "Y2.InverseRank" -> 3,
                "X2.Rank" -> 3,
                "X2.InverseRank" -> 2,
                "PrimarySizeDimension.Rank" -> 1,
                "PrimarySizeDimension.InverseRank" -> 1,
                "AspectRatio.Rank" -> 1,
                "AspectRatio.InverseRank" -> 1,
                "Area.Rank" -> 1,
                "Area.InverseRank" -> 1,
                "FilledArea.Rank" -> 1,
                "FilledArea.InverseRank" -> 1,
                "FilledProportion.Rank" -> 1,
                "FilledProportion.InverseRank" -> 1,
                "ColorUseCount.Rank" -> 1,
                "ColorUseCount.InverseRank" -> 2,
                "OutputComponentUUID" -> _String
            |>
        |>,
        <|
            "Image" -> Daniel`ARC`ARCScene[{{1}}],
            "PixelPositions" -> {{7, 7}},
            "Shape" -> <|"Name" -> "Pixel"|>,
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                <|"Name" -> "Pixel"|>,
                <|"Name" -> "Square"|>,
                <|"Name" -> "Rectangle"|>,
                <|"Name" -> "Square", "Filled" -> True|>,
                <|"Name" -> "Rectangle", "Filled" -> True|>
            },
            "Colors" -> {1},
            "Color" -> 1,
            "Position" -> {7, 7},
            "Y" -> 7,
            "X" -> 7,
            "YInverse" -> 3,
            "XInverse" -> 3,
            "Y2" -> 7,
            "X2" -> 7,
            "Y2Inverse" -> 3,
            "X2Inverse" -> 3,
            "Width" -> 1,
            "Height" -> 1,
            "Length" -> 1,
            "PrimarySizeDimension" -> "None",
            "AspectRatio" -> 1,
            "Area" -> 1,
            "FilledArea" -> 1,
            "FilledProportion" -> 1.,
            "ColorUseCount" -> 2,
            "YRelative" -> 0,
            "XRelative" -> 0,
            "Width.Rank" -> 1,
            "Width.InverseRank" -> 1,
            "Height.Rank" -> 1,
            "Height.InverseRank" -> 1,
            "Length.Rank" -> 1,
            "Length.InverseRank" -> 1,
            "Y.Rank" -> 2,
            "Y.InverseRank" -> 4,
            "X.Rank" -> 1,
            "X.InverseRank" -> 4,
            "Y2.Rank" -> 2,
            "Y2.InverseRank" -> 4,
            "X2.Rank" -> 1,
            "X2.InverseRank" -> 4,
            "PrimarySizeDimension.Rank" -> 1,
            "PrimarySizeDimension.InverseRank" -> 1,
            "AspectRatio.Rank" -> 1,
            "AspectRatio.InverseRank" -> 1,
            "Area.Rank" -> 1,
            "Area.InverseRank" -> 1,
            "FilledArea.Rank" -> 1,
            "FilledArea.InverseRank" -> 1,
            "FilledProportion.Rank" -> 1,
            "FilledProportion.InverseRank" -> 1,
            "ColorUseCount.Rank" -> 1,
            "ColorUseCount.InverseRank" -> 2,
            "OutputComponentUUID" -> _String
        |> -> <|
            "Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, 1, 7}, {-1, 7, -1}}],
            "Shape" -> Daniel`ARC`ARCScene[{{-1, 10, -1}, {10, 10, 10}, {-1, 10, -1}}],
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, 1, 7}, {-1, 7, -1}}]|>
            },
            "Position" -> {6, 6},
            "Y" -> 6,
            "X" -> 6,
            "YInverse" -> 4,
            "XInverse" -> 4,
            "X2" -> 8,
            "Y2" -> 8,
            "X2Inverse" -> 2,
            "Y2Inverse" -> 2,
            "Width" -> 3,
            "Height" -> 3,
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{-1, 7, -1}, {7, -1, 7}, {-1, 7, -1}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> -1,
                                "YInverse" -> -1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> Daniel`ARC`ARCScene[
                            {{-1, 10, -1}, {10, -1, 10}, {-1, 10, -1}}
                        ],
                        "Shapes" -> {
                            <|
                                "Image" -> Daniel`ARC`ARCScene[
                                    {{-1, 10, -1}, {10, -1, 10}, {-1, 10, -1}}
                                ]
                            |>
                        },
                        "Width" -> 3,
                        "Height" -> 3,
                        "Y" -> 6,
                        "X" -> 6,
                        "Color" -> 7
                    |>
                }
            |>,
            "Example" -> 1,
            "Input" -> <|
                "UUID" -> 0,
                "Image" -> Daniel`ARC`ARCScene[{{1}}],
                "PixelPositions" -> {{7, 7}},
                "Shape" -> <|"Name" -> "Pixel"|>,
                "Shapes" -> {
                    <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                    <|"Name" -> "Pixel"|>,
                    <|"Name" -> "Square"|>,
                    <|"Name" -> "Rectangle"|>,
                    <|"Name" -> "Square", "Filled" -> True|>,
                    <|"Name" -> "Rectangle", "Filled" -> True|>
                },
                "Colors" -> {1},
                "Color" -> 1,
                "Position" -> {7, 7},
                "Y" -> 7,
                "X" -> 7,
                "YInverse" -> 3,
                "XInverse" -> 3,
                "Y2" -> 7,
                "X2" -> 7,
                "Y2Inverse" -> 3,
                "X2Inverse" -> 3,
                "Width" -> 1,
                "Height" -> 1,
                "Length" -> 1,
                "PrimarySizeDimension" -> "None",
                "AspectRatio" -> 1,
                "Area" -> 1,
                "FilledArea" -> 1,
                "FilledProportion" -> 1.,
                "ColorUseCount" -> 2,
                "YRelative" -> 0,
                "XRelative" -> 0,
                "Width.Rank" -> 1,
                "Width.InverseRank" -> 1,
                "Height.Rank" -> 1,
                "Height.InverseRank" -> 1,
                "Length.Rank" -> 1,
                "Length.InverseRank" -> 1,
                "Y.Rank" -> 2,
                "Y.InverseRank" -> 4,
                "X.Rank" -> 1,
                "X.InverseRank" -> 4,
                "Y2.Rank" -> 2,
                "Y2.InverseRank" -> 4,
                "X2.Rank" -> 1,
                "X2.InverseRank" -> 4,
                "PrimarySizeDimension.Rank" -> 1,
                "PrimarySizeDimension.InverseRank" -> 1,
                "AspectRatio.Rank" -> 1,
                "AspectRatio.InverseRank" -> 1,
                "Area.Rank" -> 1,
                "Area.InverseRank" -> 1,
                "FilledArea.Rank" -> 1,
                "FilledArea.InverseRank" -> 1,
                "FilledProportion.Rank" -> 1,
                "FilledProportion.InverseRank" -> 1,
                "ColorUseCount.Rank" -> 1,
                "ColorUseCount.InverseRank" -> 2,
                "OutputComponentUUID" -> _String
            |>
        |>,
        <|
            "Image" -> Daniel`ARC`ARCScene[{{2}}],
            "PixelPositions" -> {{8, 2}},
            "Shape" -> <|"Name" -> "Pixel"|>,
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                <|"Name" -> "Pixel"|>,
                <|"Name" -> "Square"|>,
                <|"Name" -> "Rectangle"|>,
                <|"Name" -> "Square", "Filled" -> True|>,
                <|"Name" -> "Rectangle", "Filled" -> True|>
            },
            "Colors" -> {2},
            "Color" -> 2,
            "Position" -> {8, 2},
            "Y" -> 8,
            "X" -> 2,
            "YInverse" -> 2,
            "XInverse" -> 8,
            "Y2" -> 8,
            "X2" -> 2,
            "Y2Inverse" -> 2,
            "X2Inverse" -> 8,
            "Width" -> 1,
            "Height" -> 1,
            "Length" -> 1,
            "PrimarySizeDimension" -> "None",
            "AspectRatio" -> 1,
            "Area" -> 1,
            "FilledArea" -> 1,
            "FilledProportion" -> 1.,
            "ColorUseCount" -> 2,
            "YRelative" -> 0,
            "XRelative" -> 0,
            "Width.Rank" -> 1,
            "Width.InverseRank" -> 1,
            "Height.Rank" -> 1,
            "Height.InverseRank" -> 1,
            "Length.Rank" -> 1,
            "Length.InverseRank" -> 1,
            "Y.Rank" -> 1,
            "Y.InverseRank" -> 5,
            "X.Rank" -> 4,
            "X.InverseRank" -> 1,
            "Y2.Rank" -> 1,
            "Y2.InverseRank" -> 5,
            "X2.Rank" -> 4,
            "X2.InverseRank" -> 1,
            "PrimarySizeDimension.Rank" -> 1,
            "PrimarySizeDimension.InverseRank" -> 1,
            "AspectRatio.Rank" -> 1,
            "AspectRatio.InverseRank" -> 1,
            "Area.Rank" -> 1,
            "Area.InverseRank" -> 1,
            "FilledArea.Rank" -> 1,
            "FilledArea.InverseRank" -> 1,
            "FilledProportion.Rank" -> 1,
            "FilledProportion.InverseRank" -> 1,
            "ColorUseCount.Rank" -> 1,
            "ColorUseCount.InverseRank" -> 2,
            "OutputComponentUUID" -> _String
        |> -> <|
            "Image" -> Daniel`ARC`ARCScene[{{4, -1, 4}, {-1, 2, -1}, {4, -1, 4}}],
            "Shape" -> Daniel`ARC`ARCScene[{{10, -1, 10}, {-1, 10, -1}, {10, -1, 10}}],
            "Shapes" -> {
                <|"Image" -> Daniel`ARC`ARCScene[{{4, -1, 4}, {-1, 2, -1}, {4, -1, 4}}]|>
            },
            "Position" -> {7, 1},
            "Y" -> 7,
            "X" -> 1,
            "YInverse" -> 3,
            "XInverse" -> 9,
            "X2" -> 3,
            "Y2" -> 9,
            "X2Inverse" -> 7,
            "Y2Inverse" -> 1,
            "Width" -> 3,
            "Height" -> 3,
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> -1,
                                "YInverse" -> -1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 7,
                        "X" -> 1,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> -1,
                                "X" -> 1,
                                "YInverse" -> -1,
                                "XInverse" -> 1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 7,
                        "X" -> 3,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> 1,
                                "X" -> -1,
                                "YInverse" -> 1,
                                "XInverse" -> -1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 9,
                        "X" -> 1,
                        "Color" -> 4
                    |>,
                    <|
                        "Image" -> Daniel`ARC`ARCScene[{{4}}],
                        "Position" -> <|
                            "RelativePosition" -> <|
                                "Y" -> 1,
                                "X" -> 1,
                                "YInverse" -> 1,
                                "XInverse" -> 1
                            |>
                        |>,
                        "Shape" -> <|"Name" -> "Pixel"|>,
                        "Shapes" -> {
                            <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                            <|"Name" -> "Pixel"|>,
                            <|"Name" -> "Square"|>,
                            <|"Name" -> "Rectangle"|>,
                            <|"Name" -> "Square", "Filled" -> True|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> 1,
                        "Y" -> 9,
                        "X" -> 3,
                        "Color" -> 4
                    |>
                }
            |>,
            "Example" -> 1,
            "Input" -> <|
                "UUID" -> 0,
                "Image" -> Daniel`ARC`ARCScene[{{2}}],
                "PixelPositions" -> {{8, 2}},
                "Shape" -> <|"Name" -> "Pixel"|>,
                "Shapes" -> {
                    <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                    <|"Name" -> "Pixel"|>,
                    <|"Name" -> "Square"|>,
                    <|"Name" -> "Rectangle"|>,
                    <|"Name" -> "Square", "Filled" -> True|>,
                    <|"Name" -> "Rectangle", "Filled" -> True|>
                },
                "Colors" -> {2},
                "Color" -> 2,
                "Position" -> {8, 2},
                "Y" -> 8,
                "X" -> 2,
                "YInverse" -> 2,
                "XInverse" -> 8,
                "Y2" -> 8,
                "X2" -> 2,
                "Y2Inverse" -> 2,
                "X2Inverse" -> 8,
                "Width" -> 1,
                "Height" -> 1,
                "Length" -> 1,
                "PrimarySizeDimension" -> "None",
                "AspectRatio" -> 1,
                "Area" -> 1,
                "FilledArea" -> 1,
                "FilledProportion" -> 1.,
                "ColorUseCount" -> 2,
                "YRelative" -> 0,
                "XRelative" -> 0,
                "Width.Rank" -> 1,
                "Width.InverseRank" -> 1,
                "Height.Rank" -> 1,
                "Height.InverseRank" -> 1,
                "Length.Rank" -> 1,
                "Length.InverseRank" -> 1,
                "Y.Rank" -> 1,
                "Y.InverseRank" -> 5,
                "X.Rank" -> 4,
                "X.InverseRank" -> 1,
                "Y2.Rank" -> 1,
                "Y2.InverseRank" -> 5,
                "X2.Rank" -> 4,
                "X2.InverseRank" -> 1,
                "PrimarySizeDimension.Rank" -> 1,
                "PrimarySizeDimension.InverseRank" -> 1,
                "AspectRatio.Rank" -> 1,
                "AspectRatio.InverseRank" -> 1,
                "Area.Rank" -> 1,
                "Area.InverseRank" -> 1,
                "FilledArea.Rank" -> 1,
                "FilledArea.InverseRank" -> 1,
                "FilledProportion.Rank" -> 1,
                "FilledProportion.InverseRank" -> 1,
                "ColorUseCount.Rank" -> 1,
                "ColorUseCount.InverseRank" -> 2,
                "OutputComponentUUID" -> _String
            |>
        |>
    }
    ,
    TestID -> "ARCPruneOutputsForRuleFinding-20220719-L90VO7"
]