(*
    Tests for: Daniel`ARC`ARCReplaceRulePatternsWithGroupPatternsIfAppropriate
    
    To run these tests:
    
        << DevTools`
        << Daniel`ARC`
        RunUnitTests[Daniel`ARC`ARCReplaceRulePatternsWithGroupPatternsIfAppropriate]
    
    Author: danielb
*)

Test[
    Daniel`ARC`ARCSimplifyRules[
        Daniel`ARC`ARCReplaceRulePatternsWithGroupPatternsIfAppropriate[
            {
                <|"PrimarySizeDimension" -> "X"|> -> <|
                    "Transform" -> <|
                        "Type" -> "AddComponents",
                        "Components" -> {
                            <|
                                "Shapes" -> {
                                    <|"Name" -> "Line", "Angle" -> 0|>,
                                    <|"Name" -> "Rectangle", "Filled" -> True|>
                                },
                                "Width" -> Inactive[Plus][
                                    Daniel`ARC`ObjectValue["InputObject", "Width"],
                                    -2
                                ],
                                "Height" -> 1,
                                "Color" -> 3,
                                "Position" -> <|"RelativePosition" -> <|"Y" -> 0, "X" -> 1|>|>
                            |>
                        }
                    |>,
                    "Examples" -> {1, 3, 8},
                    "ExampleCount" -> 3,
                    "UseCount" -> 4,
                    "InputObjects" -> {
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jr",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742ju",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jv",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jz"
                    }
                |>,
                <|"PrimarySizeDimension" -> "Y"|> -> <|
                    "Transform" -> <|
                        "Type" -> "AddComponents",
                        "Components" -> {
                            <|
                                "Shapes" -> {
                                    <|"Name" -> "Line", "Angle" -> 90|>,
                                    <|"Name" -> "Rectangle", "Filled" -> True|>
                                },
                                "Width" -> 1,
                                "Height" -> Inactive[Plus][
                                    Daniel`ARC`ObjectValue["InputObject", "Height"],
                                    -2
                                ],
                                "Color" -> 3,
                                "Position" -> <|"RelativePosition" -> <|"Y" -> 1, "X" -> 0|>|>
                            |>
                        }
                    |>,
                    "Examples" -> {2, 4, 7, 8},
                    "ExampleCount" -> 4,
                    "UseCount" -> 5,
                    "InputObjects" -> {
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742js",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jw",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jt",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jx",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742jy"
                    }
                |>,
                <|"PrimarySizeDimension" -> "None"|> -> <|
                    "Same" -> True,
                    "Examples" -> {5, 6, 7, 8},
                    "ExampleCount" -> 4,
                    "UseCount" -> 5,
                    "InputObjects" -> {
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742gm",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742gw",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742gx",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742hh",
                        "e7a71aa3-1a87-4e68-a1ce-009fa20742ie"
                    }
                |>
            },
            {
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jr",
                    "Image" -> Daniel`ARC`ARCScene[{{8, -1, -1, -1, -1, -1, -1, 8}}],
                    "PixelPositions" -> {{4, 3}, {4, 10}},
                    "Colors" -> {8},
                    "Position" -> {4, 3},
                    "Y" -> 4,
                    "X" -> 3,
                    "Y2" -> 4,
                    "X2" -> 10,
                    "Width" -> 8,
                    "Height" -> 1,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742d4",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{4, 3}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {4, 3},
                            "Y" -> 4,
                            "X" -> 3,
                            "Y2" -> 4,
                            "X2" -> 3,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 1,
                            "XRank" -> 2,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 2,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742db"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742d5",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{4, 10}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {4, 10},
                            "Y" -> 4,
                            "X" -> 10,
                            "Y2" -> 4,
                            "X2" -> 10,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 1,
                            "XRank" -> 1,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742dc"
                        |>
                    },
                    "Length" -> 8,
                    "PrimarySizeDimension" -> "X",
                    "AspectRatio" -> 8,
                    "Area" -> 8,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.25
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742js",
                    "Image" -> Daniel`ARC`ARCScene[{{8}, {-1}, {-1}, {-1}, {-1}, {-1}, {8}}],
                    "PixelPositions" -> {{2, 5}, {8, 5}},
                    "Colors" -> {8},
                    "Position" -> {2, 5},
                    "Y" -> 2,
                    "X" -> 5,
                    "Y2" -> 8,
                    "X2" -> 5,
                    "Width" -> 1,
                    "Height" -> 7,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742dp",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 5}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 5},
                            "Y" -> 2,
                            "X" -> 5,
                            "Y2" -> 2,
                            "X2" -> 5,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 4,
                            "YInverseRank" -> 1,
                            "XRank" -> 2,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 4,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 2,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742e3"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ds",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{8, 5}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {8, 5},
                            "Y" -> 8,
                            "X" -> 5,
                            "Y2" -> 8,
                            "X2" -> 5,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 4,
                            "XRank" -> 2,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 4,
                            "X2Rank" -> 2,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742e6"
                        |>
                    },
                    "Length" -> 7,
                    "PrimarySizeDimension" -> "Y",
                    "AspectRatio" -> 1/7,
                    "Area" -> 7,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.2857142857142857
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jt",
                    "Image" -> Daniel`ARC`ARCScene[{{8}, {-1}, {-1}, {-1}, {8}}],
                    "PixelPositions" -> {{3, 9}, {7, 9}},
                    "Colors" -> {8},
                    "Position" -> {3, 9},
                    "Y" -> 3,
                    "X" -> 9,
                    "Y2" -> 7,
                    "X2" -> 9,
                    "Width" -> 1,
                    "Height" -> 5,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742dq",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{3, 9}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {3, 9},
                            "Y" -> 3,
                            "X" -> 9,
                            "Y2" -> 3,
                            "X2" -> 9,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 3,
                            "YInverseRank" -> 2,
                            "XRank" -> 1,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 3,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742e4"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742dr",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{7, 9}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {7, 9},
                            "Y" -> 7,
                            "X" -> 9,
                            "Y2" -> 7,
                            "X2" -> 9,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 2,
                            "YInverseRank" -> 3,
                            "XRank" -> 1,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 2,
                            "Y2InverseRank" -> 3,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742e5"
                        |>
                    },
                    "Length" -> 5,
                    "PrimarySizeDimension" -> "Y",
                    "AspectRatio" -> 1/5,
                    "Area" -> 5,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.4
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ju",
                    "Image" -> Daniel`ARC`ARCScene[{{8, -1, -1, -1, -1, -1, -1, -1, 8}}],
                    "PixelPositions" -> {{2, 2}, {2, 10}},
                    "Colors" -> {8},
                    "Position" -> {2, 2},
                    "Y" -> 2,
                    "X" -> 2,
                    "Y2" -> 2,
                    "X2" -> 10,
                    "Width" -> 9,
                    "Height" -> 1,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ev",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 2}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 2},
                            "Y" -> 2,
                            "X" -> 2,
                            "Y2" -> 2,
                            "X2" -> 2,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 2,
                            "YInverseRank" -> 1,
                            "XRank" -> 4,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 2,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 4,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742f9"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ew",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 10}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 10},
                            "Y" -> 2,
                            "X" -> 10,
                            "Y2" -> 2,
                            "X2" -> 10,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 2,
                            "YInverseRank" -> 1,
                            "XRank" -> 1,
                            "XInverseRank" -> 4,
                            "Y2Rank" -> 2,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 4,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742fa"
                        |>
                    },
                    "Length" -> 9,
                    "PrimarySizeDimension" -> "X",
                    "AspectRatio" -> 9,
                    "Area" -> 9,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.2222222222222222
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jv",
                    "Image" -> Daniel`ARC`ARCScene[{{8, -1, -1, -1, -1, 8}}],
                    "PixelPositions" -> {{9, 3}, {9, 8}},
                    "Colors" -> {8},
                    "Position" -> {9, 3},
                    "Y" -> 9,
                    "X" -> 3,
                    "Y2" -> 9,
                    "X2" -> 8,
                    "Width" -> 6,
                    "Height" -> 1,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ex",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{9, 3}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {9, 3},
                            "Y" -> 9,
                            "X" -> 3,
                            "Y2" -> 9,
                            "X2" -> 3,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 2,
                            "XRank" -> 3,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 3,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742fb"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ey",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{9, 8}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {9, 8},
                            "Y" -> 9,
                            "X" -> 8,
                            "Y2" -> 9,
                            "X2" -> 8,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 2,
                            "XRank" -> 2,
                            "XInverseRank" -> 3,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 2,
                            "X2InverseRank" -> 3,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742fc"
                        |>
                    },
                    "Length" -> 6,
                    "PrimarySizeDimension" -> "X",
                    "AspectRatio" -> 6,
                    "Area" -> 6,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.3333333333333333
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jw",
                    "Image" -> Daniel`ARC`ARCScene[{{8}, {-1}, {-1}, {-1}, {-1}, {-1}, {8}}],
                    "PixelPositions" -> {{2, 3}, {8, 3}},
                    "Colors" -> {8},
                    "Position" -> {2, 3},
                    "Y" -> 2,
                    "X" -> 3,
                    "Y2" -> 8,
                    "X2" -> 3,
                    "Width" -> 1,
                    "Height" -> 7,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742g1",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 3}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 3},
                            "Y" -> 2,
                            "X" -> 3,
                            "Y2" -> 2,
                            "X2" -> 3,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 2,
                            "YInverseRank" -> 1,
                            "XRank" -> 1,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 2,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742g8"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742g2",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{8, 3}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {8, 3},
                            "Y" -> 8,
                            "X" -> 3,
                            "Y2" -> 8,
                            "X2" -> 3,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 2,
                            "XRank" -> 1,
                            "XInverseRank" -> 1,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 1,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742g9"
                        |>
                    },
                    "Length" -> 7,
                    "PrimarySizeDimension" -> "Y",
                    "AspectRatio" -> 1/7,
                    "Area" -> 7,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.2857142857142857
                |>,
                <|
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742gm",
                    "Image" -> Daniel`ARC`ARCScene[{{8}}],
                    "PixelPositions" -> {{2, 2}},
                    "Shape" -> <|"Name" -> "Pixel"|>,
                    "Shapes" -> {
                        <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                        <|"Name" -> "Pixel"|>,
                        <|"Name" -> "Square"|>,
                        <|"Name" -> "Rectangle"|>,
                        <|"Name" -> "Square", "Filled" -> True|>,
                        <|"Name" -> "Rectangle", "Filled" -> True|>
                    },
                    "Colors" -> {8},
                    "Position" -> {2, 2},
                    "Y" -> 2,
                    "X" -> 2,
                    "Y2" -> 2,
                    "X2" -> 2,
                    "Width" -> 1,
                    "Height" -> 1,
                    "Length" -> 1,
                    "PrimarySizeDimension" -> "None",
                    "AspectRatio" -> 1,
                    "Area" -> 1,
                    "FilledArea" -> 1,
                    "FilledProportion" -> 1.,
                    "WidthRank" -> 1,
                    "WidthInverseRank" -> 1,
                    "HeightRank" -> 1,
                    "HeightInverseRank" -> 1,
                    "LengthRank" -> 1,
                    "LengthInverseRank" -> 1,
                    "YRank" -> 1,
                    "YInverseRank" -> 1,
                    "XRank" -> 1,
                    "XInverseRank" -> 1,
                    "Y2Rank" -> 1,
                    "Y2InverseRank" -> 1,
                    "X2Rank" -> 1,
                    "X2InverseRank" -> 1,
                    "PrimarySizeDimensionRank" -> 1,
                    "PrimarySizeDimensionInverseRank" -> 1,
                    "AspectRatioRank" -> 1,
                    "AspectRatioInverseRank" -> 1
                |>,
                <|
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742gw",
                    "Image" -> Daniel`ARC`ARCScene[{{8}}],
                    "PixelPositions" -> {{2, 2}},
                    "Shape" -> <|"Name" -> "Pixel"|>,
                    "Shapes" -> {
                        <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                        <|"Name" -> "Pixel"|>,
                        <|"Name" -> "Square"|>,
                        <|"Name" -> "Rectangle"|>,
                        <|"Name" -> "Square", "Filled" -> True|>,
                        <|"Name" -> "Rectangle", "Filled" -> True|>
                    },
                    "Colors" -> {8},
                    "Position" -> {2, 2},
                    "Y" -> 2,
                    "X" -> 2,
                    "Y2" -> 2,
                    "X2" -> 2,
                    "Width" -> 1,
                    "Height" -> 1,
                    "Length" -> 1,
                    "PrimarySizeDimension" -> "None",
                    "AspectRatio" -> 1,
                    "Area" -> 1,
                    "FilledArea" -> 1,
                    "FilledProportion" -> 1.,
                    "WidthRank" -> 1,
                    "WidthInverseRank" -> 1,
                    "HeightRank" -> 1,
                    "HeightInverseRank" -> 1,
                    "LengthRank" -> 1,
                    "LengthInverseRank" -> 1,
                    "YRank" -> 2,
                    "YInverseRank" -> 1,
                    "XRank" -> 2,
                    "XInverseRank" -> 1,
                    "Y2Rank" -> 2,
                    "Y2InverseRank" -> 1,
                    "X2Rank" -> 2,
                    "X2InverseRank" -> 1,
                    "PrimarySizeDimensionRank" -> 1,
                    "PrimarySizeDimensionInverseRank" -> 1,
                    "AspectRatioRank" -> 1,
                    "AspectRatioInverseRank" -> 1
                |>,
                <|
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742gx",
                    "Image" -> Daniel`ARC`ARCScene[{{8}}],
                    "PixelPositions" -> {{4, 5}},
                    "Shape" -> <|"Name" -> "Pixel"|>,
                    "Shapes" -> {
                        <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                        <|"Name" -> "Pixel"|>,
                        <|"Name" -> "Square"|>,
                        <|"Name" -> "Rectangle"|>,
                        <|"Name" -> "Square", "Filled" -> True|>,
                        <|"Name" -> "Rectangle", "Filled" -> True|>
                    },
                    "Colors" -> {8},
                    "Position" -> {4, 5},
                    "Y" -> 4,
                    "X" -> 5,
                    "Y2" -> 4,
                    "X2" -> 5,
                    "Width" -> 1,
                    "Height" -> 1,
                    "Length" -> 1,
                    "PrimarySizeDimension" -> "None",
                    "AspectRatio" -> 1,
                    "Area" -> 1,
                    "FilledArea" -> 1,
                    "FilledProportion" -> 1.,
                    "WidthRank" -> 1,
                    "WidthInverseRank" -> 1,
                    "HeightRank" -> 1,
                    "HeightInverseRank" -> 1,
                    "LengthRank" -> 1,
                    "LengthInverseRank" -> 1,
                    "YRank" -> 1,
                    "YInverseRank" -> 2,
                    "XRank" -> 1,
                    "XInverseRank" -> 2,
                    "Y2Rank" -> 1,
                    "Y2InverseRank" -> 2,
                    "X2Rank" -> 1,
                    "X2InverseRank" -> 2,
                    "PrimarySizeDimensionRank" -> 1,
                    "PrimarySizeDimensionInverseRank" -> 1,
                    "AspectRatioRank" -> 1,
                    "AspectRatioInverseRank" -> 1
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jx",
                    "Image" -> Daniel`ARC`ARCScene[{{8}, {-1}, {-1}, {-1}, {-1}, {8}}],
                    "PixelPositions" -> {{2, 4}, {7, 4}},
                    "Colors" -> {8},
                    "Position" -> {2, 4},
                    "Y" -> 2,
                    "X" -> 4,
                    "Y2" -> 7,
                    "X2" -> 4,
                    "Width" -> 1,
                    "Height" -> 6,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742hg",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 4}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 4},
                            "Y" -> 2,
                            "X" -> 4,
                            "Y2" -> 2,
                            "X2" -> 4,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 3,
                            "YInverseRank" -> 1,
                            "XRank" -> 1,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 3,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742hq"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742hi",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{7, 4}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {7, 4},
                            "Y" -> 7,
                            "X" -> 4,
                            "Y2" -> 7,
                            "X2" -> 4,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 3,
                            "XRank" -> 1,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 3,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742hs"
                        |>
                    },
                    "Length" -> 6,
                    "PrimarySizeDimension" -> "Y",
                    "AspectRatio" -> 1/6,
                    "Area" -> 6,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.3333333333333333
                |>,
                <|
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742hh",
                    "Image" -> Daniel`ARC`ARCScene[{{8}}],
                    "PixelPositions" -> {{4, 2}},
                    "Shape" -> <|"Name" -> "Pixel"|>,
                    "Shapes" -> {
                        <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                        <|"Name" -> "Pixel"|>,
                        <|"Name" -> "Square"|>,
                        <|"Name" -> "Rectangle"|>,
                        <|"Name" -> "Square", "Filled" -> True|>,
                        <|"Name" -> "Rectangle", "Filled" -> True|>
                    },
                    "Colors" -> {8},
                    "Position" -> {4, 2},
                    "Y" -> 4,
                    "X" -> 2,
                    "Y2" -> 4,
                    "X2" -> 2,
                    "Width" -> 1,
                    "Height" -> 1,
                    "Length" -> 1,
                    "PrimarySizeDimension" -> "None",
                    "AspectRatio" -> 1,
                    "Area" -> 1,
                    "FilledArea" -> 1,
                    "FilledProportion" -> 1.,
                    "WidthRank" -> 1,
                    "WidthInverseRank" -> 1,
                    "HeightRank" -> 1,
                    "HeightInverseRank" -> 1,
                    "LengthRank" -> 1,
                    "LengthInverseRank" -> 1,
                    "YRank" -> 2,
                    "YInverseRank" -> 2,
                    "XRank" -> 2,
                    "XInverseRank" -> 1,
                    "Y2Rank" -> 2,
                    "Y2InverseRank" -> 2,
                    "X2Rank" -> 2,
                    "X2InverseRank" -> 1,
                    "PrimarySizeDimensionRank" -> 1,
                    "PrimarySizeDimensionInverseRank" -> 1,
                    "AspectRatioRank" -> 1,
                    "AspectRatioInverseRank" -> 1
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jy",
                    "Image" -> Daniel`ARC`ARCScene[
                        {{8}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {8}}
                    ],
                    "PixelPositions" -> {{2, 4}, {10, 4}},
                    "Colors" -> {8},
                    "Position" -> {2, 4},
                    "Y" -> 2,
                    "X" -> 4,
                    "Y2" -> 10,
                    "X2" -> 4,
                    "Width" -> 1,
                    "Height" -> 9,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ib",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{2, 4}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {2, 4},
                            "Y" -> 2,
                            "X" -> 4,
                            "Y2" -> 2,
                            "X2" -> 4,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 4,
                            "YInverseRank" -> 1,
                            "XRank" -> 3,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 4,
                            "Y2InverseRank" -> 1,
                            "X2Rank" -> 3,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742is"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742if",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{10, 4}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {10, 4},
                            "Y" -> 10,
                            "X" -> 4,
                            "Y2" -> 10,
                            "X2" -> 4,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 1,
                            "YInverseRank" -> 4,
                            "XRank" -> 3,
                            "XInverseRank" -> 2,
                            "Y2Rank" -> 1,
                            "Y2InverseRank" -> 4,
                            "X2Rank" -> 3,
                            "X2InverseRank" -> 2,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742iw"
                        |>
                    },
                    "Length" -> 9,
                    "PrimarySizeDimension" -> "Y",
                    "AspectRatio" -> 1/9,
                    "Area" -> 9,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.2222222222222222
                |>,
                <|
                    "Type" -> "Group",
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742jz",
                    "Image" -> Daniel`ARC`ARCScene[{{8, -1, -1, -1, 8}}],
                    "PixelPositions" -> {{5, 7}, {5, 11}},
                    "Colors" -> {8},
                    "Position" -> {5, 7},
                    "Y" -> 5,
                    "X" -> 7,
                    "Y2" -> 5,
                    "X2" -> 11,
                    "Width" -> 5,
                    "Height" -> 1,
                    "Components" -> {
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ic",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{5, 7}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {5, 7},
                            "Y" -> 5,
                            "X" -> 7,
                            "Y2" -> 5,
                            "X2" -> 7,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 3,
                            "YInverseRank" -> 2,
                            "XRank" -> 2,
                            "XInverseRank" -> 3,
                            "Y2Rank" -> 3,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 2,
                            "X2InverseRank" -> 3,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742it"
                        |>,
                        <|
                            "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742id",
                            "Image" -> Daniel`ARC`ARCScene[{{8}}],
                            "PixelPositions" -> {{5, 11}},
                            "Shape" -> <|"Name" -> "Pixel"|>,
                            "Shapes" -> {
                                <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                                <|"Name" -> "Pixel"|>,
                                <|"Name" -> "Square"|>,
                                <|"Name" -> "Rectangle"|>,
                                <|"Name" -> "Square", "Filled" -> True|>,
                                <|"Name" -> "Rectangle", "Filled" -> True|>
                            },
                            "Colors" -> {8},
                            "Position" -> {5, 11},
                            "Y" -> 5,
                            "X" -> 11,
                            "Y2" -> 5,
                            "X2" -> 11,
                            "Width" -> 1,
                            "Height" -> 1,
                            "Length" -> 1,
                            "PrimarySizeDimension" -> "None",
                            "AspectRatio" -> 1,
                            "Area" -> 1,
                            "FilledArea" -> 1,
                            "FilledProportion" -> 1.,
                            "WidthRank" -> 1,
                            "WidthInverseRank" -> 1,
                            "HeightRank" -> 1,
                            "HeightInverseRank" -> 1,
                            "LengthRank" -> 1,
                            "LengthInverseRank" -> 1,
                            "YRank" -> 3,
                            "YInverseRank" -> 2,
                            "XRank" -> 1,
                            "XInverseRank" -> 4,
                            "Y2Rank" -> 3,
                            "Y2InverseRank" -> 2,
                            "X2Rank" -> 1,
                            "X2InverseRank" -> 4,
                            "PrimarySizeDimensionRank" -> 1,
                            "PrimarySizeDimensionInverseRank" -> 1,
                            "AspectRatioRank" -> 1,
                            "AspectRatioInverseRank" -> 1,
                            "OutputComponentUUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742iu"
                        |>
                    },
                    "Length" -> 5,
                    "PrimarySizeDimension" -> "X",
                    "AspectRatio" -> 5,
                    "Area" -> 5,
                    "FilledArea" -> 2,
                    "FilledProportion" -> 0.4
                |>,
                <|
                    "UUID" -> "e7a71aa3-1a87-4e68-a1ce-009fa20742ie",
                    "Image" -> Daniel`ARC`ARCScene[{{8}}],
                    "PixelPositions" -> {{6, 2}},
                    "Shape" -> <|"Name" -> "Pixel"|>,
                    "Shapes" -> {
                        <|"Image" -> Daniel`ARC`ARCScene[{{10}}]|>,
                        <|"Name" -> "Pixel"|>,
                        <|"Name" -> "Square"|>,
                        <|"Name" -> "Rectangle"|>,
                        <|"Name" -> "Square", "Filled" -> True|>,
                        <|"Name" -> "Rectangle", "Filled" -> True|>
                    },
                    "Colors" -> {8},
                    "Position" -> {6, 2},
                    "Y" -> 6,
                    "X" -> 2,
                    "Y2" -> 6,
                    "X2" -> 2,
                    "Width" -> 1,
                    "Height" -> 1,
                    "Length" -> 1,
                    "PrimarySizeDimension" -> "None",
                    "AspectRatio" -> 1,
                    "Area" -> 1,
                    "FilledArea" -> 1,
                    "FilledProportion" -> 1.,
                    "WidthRank" -> 1,
                    "WidthInverseRank" -> 1,
                    "HeightRank" -> 1,
                    "HeightInverseRank" -> 1,
                    "LengthRank" -> 1,
                    "LengthInverseRank" -> 1,
                    "YRank" -> 2,
                    "YInverseRank" -> 3,
                    "XRank" -> 4,
                    "XInverseRank" -> 1,
                    "Y2Rank" -> 2,
                    "Y2InverseRank" -> 3,
                    "X2Rank" -> 4,
                    "X2InverseRank" -> 1,
                    "PrimarySizeDimensionRank" -> 1,
                    "PrimarySizeDimensionInverseRank" -> 1,
                    "AspectRatioRank" -> 1,
                    "AspectRatioInverseRank" -> 1
                |>
            }
        ]
    ]
    ,
    {
        <|
            "Type" -> "Group",
            "Colors" -> {8},
            "Height" -> 1,
            "PrimarySizeDimension" -> "X",
            "FilledArea" -> 2
        |> -> <|
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Shapes" -> {
                            <|"Name" -> "Line", "Angle" -> 0|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> Inactive[Plus][
                            Daniel`ARC`ObjectValue["InputObject", "Width"],
                            -2
                        ],
                        "Height" -> 1,
                        "Color" -> 3,
                        "Position" -> <|"RelativePosition" -> <|"Y" -> 0, "X" -> 1|>|>
                    |>
                }
            |>
        |>,
        <|
            "Type" -> "Group",
            "Colors" -> {8},
            "Width" -> 1,
            "PrimarySizeDimension" -> "Y",
            "FilledArea" -> 2
        |> -> <|
            "Transform" -> <|
                "Type" -> "AddComponents",
                "Components" -> {
                    <|
                        "Shapes" -> {
                            <|"Name" -> "Line", "Angle" -> 90|>,
                            <|"Name" -> "Rectangle", "Filled" -> True|>
                        },
                        "Width" -> 1,
                        "Height" -> Inactive[Plus][
                            Daniel`ARC`ObjectValue["InputObject", "Height"],
                            -2
                        ],
                        "Color" -> 3,
                        "Position" -> <|"RelativePosition" -> <|"Y" -> 1, "X" -> 0|>|>
                    |>
                }
            |>
        |>,
        <|"PrimarySizeDimension" -> "None"|> -> <|"Same" -> True|>
    }
    ,
    TestID -> "ARCReplaceRulePatternsWithGroupPatternsIfAppropriate-20220812-OPIWNI"
]